version: "3"
services:
  react-app:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always

  node-app:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always
    depends_on:
      - mysql
    environment:
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      MYSQL_USER: root
      MYSQL_PASSWORD: Mangekyo$haringan19
      MYSQL_DATABASE: online_exam_application

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: Mangekyo$haringan19
      MYSQL_DATABASE: online_exam_application
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: always

volumes:
  mysql-data:
